// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sousxxsegqwbqjghkwom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvdXN4eHNlZ3F3YnFqZ2hrd29tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODg0MjUsImV4cCI6MjA2NzQ2NDQyNX0.a9iDev6GjAu_YOmn4nbwJPHPpfqzjAattTbVPIuVAPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});